FROM node:20.11.1
RUN apt-get update && \
    apt-get install -y postgresql-client

WORKDIR /app
COPY backend/package*.json ./
RUN npm install
COPY backend/prisma ./prisma
COPY ./backend/. .
RUN npx prisma generate
RUN npm run build
COPY wait-for-db.sh /app/wait-for-db.sh
RUN chmod +x /app/wait-for-db.sh

EXPOSE 3000
CMD ["sh", "-c", "./wait-for-db.sh db npx prisma migrate deploy && npm run start:dev"]
